export const SituacaoClinica = {
    fisico: [
        { nome: "Cuidados paliativos", descricao: " Assistenciais oferecidos para todo paciente que tenha uma doença que necessite de cuidados visando melhor qualidade de vida através da prevenção e alivio do sofrimento imposto pela doença " },
        { nome: "Doenças trato gastrointestinal", descricao: " O trato gastrointestinal é composto pela boca, faringe, esôfago e estômago, intestino delgado e intestino grosso e podem desenvolver doenças como doença de Crohn, síndrome do intestino irritável, retocolite ulcerosa, obstipação. Tais doenças podem ser acompanhadas de dores, resultantes da inflamação ou até mesmo deterioração de alguns dos órgãos do sistema digestivo " },
        { nome: "Doenças cardiovasculares", descricao: "As doenças cardiovasculares afetam o sistema circulatório, ou seja, o coração e os vasos sanguíneos (artérias, veias e vasos capilares Entre estas doenças estão as doenças arteriais coronárias, como a angina de peito e o enfarte agudo do miocárdio, acidentes vasculares cerebrais (AVC), cardiopatia hipertensiva, febre reumática, miocardiopatia, arritmia cardíaca, cardiopatia congénita, valvulopatias, cardite, aneurisma da aorta, doença arterial periférica e trombose venosa." },
        { nome: "Doenças infectocontagiosas", descricao: " Doenças causadas por microrganismos como vírus, bactérias, protozoários ou fungos. Podem ser adquiridas por meio do contato direto com o agente infeccioso, contato com água ou alimentos contaminados, através da via respiratória, sexual ou por meio de ferimentos causados por animais " },
        { nome: "Doença respiratórias", descricao: " Aquelas que atingem órgãos do sistema respiratório (pulmões, boca, faringe, fossas nasais, laringe, brônquios, traquéia, diafragma, bronquíolos e alvéolos pulmonares. As enfermidades do sistema respiratório mais frequentes são: bronquite, rinite, sinusite, asma, gripe, resfriado, faringite, enfisema pulmonar, câncer de pulmão, fribose pulmonar, tuberculose e pneumonia " },
        { nome: "Feridas", descricao: " Agressões que ocorrem na pele. As feridas podem ser classificadas quanto ao seu agente causador em: cortantes ou incisas, contusas, pérfuro-contusas, pérfuro-incisas, escoriações, hematomas " },
        { nome: "Mobilidade reduzida", descricao: "É a situação do indivíduo cujos movimentos são limitados em consequência da idade, de deficiência física (sensorial ou de locomoção, que pode ser permanente ou momentânea) ou mental, necessitando de atenção especial ou adaptações nos ambientes" },
        { nome: "Doenças do Sistema Urinário", descricao: " O Sistema Urinário é responsável pela produção e eliminação da urina, possui a função de filtrar as impurezas do sangue que circula no organismo. Essse sistema é composto por dois rins e pelas vias urinárias, formada por dois ureteres, a bexiga urinária e a uretra" }
    ],
    assistencia: [
        {nome: "Cuidados Paliativos", descricao: ""},
        {nome: "Constipação", descricao: ""},
        {nome: "Disfunção Cognitiva", descricao: ""},
        {nome: "Doença Cardiovascular", descricao: ""},
        {nome: "Doenças Infectocontagiosas", descricao: ""},
        {nome: "Doença Osteomuscular", descricao: ""},
        {nome: "Doença Respiratoria", descricao: ""},
        {nome: "Feridas", descricao: ""},
        {nome: "Imobiliddade", descricao: ""},
        {nome: "Infecção Trato Urinario", descricao: ""},
        {nome: "Neoplasia", descricao: ""},
        {nome: "Pós Cirurgico", descricao: ""},
        {nome: "Pré Cirurgico", descricao: ""},
        {nome: "Reabilitação Neurofunional e Motora", descricao: ""},
        {nome: "Reabilitação Nutricional", descricao: ""},
        {nome: "Sindrome da Fragilidade", descricao: ""},
        {nome: "Sindrome Neurologica da Infancia ao Envelhecimento", descricao: ""},
        {nome: "Transtorno Saude Mental", descricao: ""},
        // "(opção descrever e escrever o profissional)"
    ],
    prevencao: [
        {nome: "Cuidados Paliativos Preventivos(acamados, pós / pré - cirúrgicos)", descricao: ""},
        {nome: "Habilitação e Desempenho(atletas)", descricao: ""},
        {nome: "Personal Trainer (Acompanhamento ginásio)", descricao: ""},
        {nome: "Prevencao Doença e Dores Osteomusculares e Articulares", descricao: ""},
        {nome: "Prevenção Contra Queda", descricao: ""},
        {nome: "Precenção Contra Doenças Infectocontagiosas", descricao: ""},
        {nome: "Treinamento para Prova Física", descricao: ""},
    ],
    estetica: [
        {nome: "Cuidados Paliativos Preventivos(acamados, pós / pré - cirúrgicos)", descricao: ""},
        {nome: "Habilitação e Desempenho(atletas)", descricao: ""},
        {nome: "Personal Trainer (Acompanhamento ginásio)", descricao: ""},
        {nome: "Prevencao Doença e Dores Osteomusculares e Articulares", descricao: ""},
        {nome: "Prevenção Contra Queda", descricao: ""},
        {nome: "Precenção Contra Doenças Infectocontagiosas", descricao: ""},
        {nome: "Treinamento para Prova Física", descricao: ""},
    ],
    pets: [
        {nome: "Cuidados Paliativos Preventivos(acamados, pós / pré - cirúrgicos)", descricao: ""},
        {nome: "Habilitação e Desempenho(atletas)", descricao: ""},
        {nome: "Personal Trainer (Acompanhamento ginásio)", descricao: ""},
        {nome: "Prevencao Doença e Dores Osteomusculares e Articulares", descricao: ""},
        {nome: "Prevenção Contra Queda", descricao: ""},
        {nome: "Precenção Contra Doenças Infectocontagiosas", descricao: ""},
        {nome: "Treinamento para Prova Física", descricao: ""},
    ]
}