import { municipios } from "./municipios";

export const UFs = [
    { sigla: 'AC', nome: 'Acre', municipios: municipios.df },
    { sigla: 'AL', nome: 'Alagoas', municipios: municipios.df },
    { sigla: 'AP', nome: 'Amapá', municipios: municipios.df },
    { sigla: 'AM', nome: 'Amazonas', municipios: municipios.df },
    { sigla: 'BA', nome: 'Bahia', municipios: municipios.df },
    { sigla: 'CE', nome: 'Ceará', municipios: municipios.df },
    { sigla: 'DF', nome: 'Distrito Federal', municipios: municipios.df },
    { sigla: 'ES', nome: 'Espírito Santo', municipios: municipios.df },
    { sigla: 'GO', nome: 'Goiás', municipios: municipios.df },
    { sigla: 'MA', nome: 'Maranhão', municipios: municipios.df },
    { sigla: 'MT', nome: 'Mato Grosso', municipios: municipios.df },
    { sigla: 'MS', nome: 'Mato Grosso do Sul', municipios: municipios.df },
    { sigla: 'MG', nome: 'Minas Gerais', municipios: municipios.df },
    { sigla: 'PA', nome: 'Pará', municipios: municipios.df },
    { sigla: 'PB', nome: 'Paraíba', municipios: municipios.df },
    { sigla: 'PR', nome: 'Paraná', municipios: municipios.df },
    { sigla: 'PE', nome: 'Pernambuco', municipios: municipios.df },
    { sigla: 'PI', nome: 'Piauí', municipios: municipios.df },
    { sigla: 'RJ', nome: 'Rio de Janeiro', municipios: municipios.df },
    { sigla: 'RN', nome: 'Rio Grande do Norte', municipios: municipios.df },
    { sigla: 'RS', nome: 'Rio Grande do Sul', municipios: municipios.df },
    { sigla: 'RO', nome: 'Rondônia', municipios: municipios.df },
    { sigla: 'RR', nome: 'Roraima', municipios: municipios.df },
    { sigla: 'SC', nome: 'Santa Catarina', municipios: municipios.df },
    { sigla: 'SP', nome: 'São Paulo', municipios: municipios.df },
    { sigla: 'SE', nome: 'Sergipe', municipios: municipios.df },
    { sigla: 'TO', nome: 'Tocantins', municipios: municipios.df },
];